namespace:
  name: prod

metadata:
  name: techtrends

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 7

resources:
  requests:
    cpu: "350m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

containerPort:
  port: 7111

livenessProbe:
  path: /healthz
  port: 7111

readinessProbe:
  path: /healthz
  port: 7111